// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "octopus/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockShortLinkServiceInterface is a mock of ShortLinkServiceInterface interface.
type MockShortLinkServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockShortLinkServiceInterfaceMockRecorder
}

// MockShortLinkServiceInterfaceMockRecorder is the mock recorder for MockShortLinkServiceInterface.
type MockShortLinkServiceInterfaceMockRecorder struct {
	mock *MockShortLinkServiceInterface
}

// NewMockShortLinkServiceInterface creates a new mock instance.
func NewMockShortLinkServiceInterface(ctrl *gomock.Controller) *MockShortLinkServiceInterface {
	mock := &MockShortLinkServiceInterface{ctrl: ctrl}
	mock.recorder = &MockShortLinkServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortLinkServiceInterface) EXPECT() *MockShortLinkServiceInterfaceMockRecorder {
	return m.recorder
}

// ExpandURL mocks base method.
func (m *MockShortLinkServiceInterface) ExpandURL(ctx context.Context, shortCode string, queryParams map[string]string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpandURL", ctx, shortCode, queryParams)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExpandURL indicates an expected call of ExpandURL.
func (mr *MockShortLinkServiceInterfaceMockRecorder) ExpandURL(ctx, shortCode, queryParams interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpandURL", reflect.TypeOf((*MockShortLinkServiceInterface)(nil).ExpandURL), ctx, shortCode, queryParams)
}

// Generate mocks base method.
func (m *MockShortLinkServiceInterface) Generate(ctx context.Context, req *model.GenerateRequest) (*model.GenerateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx, req)
	ret0, _ := ret[0].(*model.GenerateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockShortLinkServiceInterfaceMockRecorder) Generate(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockShortLinkServiceInterface)(nil).Generate), ctx, req)
}

// Get mocks base method.
func (m *MockShortLinkServiceInterface) Get(ctx context.Context, shortCode string) (*model.ShortLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, shortCode)
	ret0, _ := ret[0].(*model.ShortLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockShortLinkServiceInterfaceMockRecorder) Get(ctx, shortCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockShortLinkServiceInterface)(nil).Get), ctx, shortCode)
}

// MockAnalyticsServiceInterface is a mock of AnalyticsServiceInterface interface.
type MockAnalyticsServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyticsServiceInterfaceMockRecorder
}

// MockAnalyticsServiceInterfaceMockRecorder is the mock recorder for MockAnalyticsServiceInterface.
type MockAnalyticsServiceInterfaceMockRecorder struct {
	mock *MockAnalyticsServiceInterface
}

// NewMockAnalyticsServiceInterface creates a new mock instance.
func NewMockAnalyticsServiceInterface(ctrl *gomock.Controller) *MockAnalyticsServiceInterface {
	mock := &MockAnalyticsServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAnalyticsServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalyticsServiceInterface) EXPECT() *MockAnalyticsServiceInterfaceMockRecorder {
	return m.recorder
}

// GetAnalytics mocks base method.
func (m *MockAnalyticsServiceInterface) GetAnalytics(ctx context.Context, shortCode string) (*model.AnalyticsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnalytics", ctx, shortCode)
	ret0, _ := ret[0].(*model.AnalyticsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAnalytics indicates an expected call of GetAnalytics.
func (mr *MockAnalyticsServiceInterfaceMockRecorder) GetAnalytics(ctx, shortCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnalytics", reflect.TypeOf((*MockAnalyticsServiceInterface)(nil).GetAnalytics), ctx, shortCode)
}

// GetStats mocks base method.
func (m *MockAnalyticsServiceInterface) GetStats(ctx context.Context, shortCode string) (*model.Stats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx, shortCode)
	ret0, _ := ret[0].(*model.Stats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockAnalyticsServiceInterfaceMockRecorder) GetStats(ctx, shortCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockAnalyticsServiceInterface)(nil).GetStats), ctx, shortCode)
}

// RecordAccess mocks base method.
func (m *MockAnalyticsServiceInterface) RecordAccess(ctx context.Context, shortCode, clientIP, userAgent, referer string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordAccess", ctx, shortCode, clientIP, userAgent, referer)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordAccess indicates an expected call of RecordAccess.
func (mr *MockAnalyticsServiceInterfaceMockRecorder) RecordAccess(ctx, shortCode, clientIP, userAgent, referer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordAccess", reflect.TypeOf((*MockAnalyticsServiceInterface)(nil).RecordAccess), ctx, shortCode, clientIP, userAgent, referer)
}

// MockBloomServiceInterface is a mock of BloomServiceInterface interface.
type MockBloomServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBloomServiceInterfaceMockRecorder
}

// MockBloomServiceInterfaceMockRecorder is the mock recorder for MockBloomServiceInterface.
type MockBloomServiceInterfaceMockRecorder struct {
	mock *MockBloomServiceInterface
}

// NewMockBloomServiceInterface creates a new mock instance.
func NewMockBloomServiceInterface(ctrl *gomock.Controller) *MockBloomServiceInterface {
	mock := &MockBloomServiceInterface{ctrl: ctrl}
	mock.recorder = &MockBloomServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBloomServiceInterface) EXPECT() *MockBloomServiceInterfaceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockBloomServiceInterface) Add(ctx context.Context, shortCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, shortCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockBloomServiceInterfaceMockRecorder) Add(ctx, shortCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockBloomServiceInterface)(nil).Add), ctx, shortCode)
}

// Exists mocks base method.
func (m *MockBloomServiceInterface) Exists(ctx context.Context, shortCode string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, shortCode)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockBloomServiceInterfaceMockRecorder) Exists(ctx, shortCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockBloomServiceInterface)(nil).Exists), ctx, shortCode)
}

// GetCapacity mocks base method.
func (m *MockBloomServiceInterface) GetCapacity() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCapacity")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetCapacity indicates an expected call of GetCapacity.
func (mr *MockBloomServiceInterfaceMockRecorder) GetCapacity() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCapacity", reflect.TypeOf((*MockBloomServiceInterface)(nil).GetCapacity))
}

// IsAvailable mocks base method.
func (m *MockBloomServiceInterface) IsAvailable(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAvailable", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAvailable indicates an expected call of IsAvailable.
func (mr *MockBloomServiceInterfaceMockRecorder) IsAvailable(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAvailable", reflect.TypeOf((*MockBloomServiceInterface)(nil).IsAvailable), ctx)
}

// Reset mocks base method.
func (m *MockBloomServiceInterface) Reset(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reset", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reset indicates an expected call of Reset.
func (mr *MockBloomServiceInterfaceMockRecorder) Reset(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockBloomServiceInterface)(nil).Reset), ctx)
}
