// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "octopus/internal/model"
	reflect "reflect"
	time "time"

	redis "github.com/redis/go-redis/v9"

	gomock "github.com/golang/mock/gomock"
)

// MockMySQLRepositoryInterface is a mock of MySQLRepositoryInterface interface.
type MockMySQLRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMySQLRepositoryInterfaceMockRecorder
}

// MockMySQLRepositoryInterfaceMockRecorder is the mock recorder for MockMySQLRepositoryInterface.
type MockMySQLRepositoryInterfaceMockRecorder struct {
	mock *MockMySQLRepositoryInterface
}

// NewMockMySQLRepositoryInterface creates a new mock instance.
func NewMockMySQLRepositoryInterface(ctrl *gomock.Controller) *MockMySQLRepositoryInterface {
	mock := &MockMySQLRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockMySQLRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMySQLRepositoryInterface) EXPECT() *MockMySQLRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CheckExistsByCode mocks base method.
func (m *MockMySQLRepositoryInterface) CheckExistsByCode(ctx context.Context, shortCode string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExistsByCode", ctx, shortCode)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckExistsByCode indicates an expected call of CheckExistsByCode.
func (mr *MockMySQLRepositoryInterfaceMockRecorder) CheckExistsByCode(ctx, shortCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExistsByCode", reflect.TypeOf((*MockMySQLRepositoryInterface)(nil).CheckExistsByCode), ctx, shortCode)
}

// CleanupExpiredLinks mocks base method.
func (m *MockMySQLRepositoryInterface) CleanupExpiredLinks(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExpiredLinks", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupExpiredLinks indicates an expected call of CleanupExpiredLinks.
func (mr *MockMySQLRepositoryInterfaceMockRecorder) CleanupExpiredLinks(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpiredLinks", reflect.TypeOf((*MockMySQLRepositoryInterface)(nil).CleanupExpiredLinks), ctx)
}

// Close mocks base method.
func (m *MockMySQLRepositoryInterface) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockMySQLRepositoryInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMySQLRepositoryInterface)(nil).Close))
}

// GetAccessLogs mocks base method.
func (m *MockMySQLRepositoryInterface) GetAccessLogs(ctx context.Context, shortCode string, limit int) ([]model.AccessLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessLogs", ctx, shortCode, limit)
	ret0, _ := ret[0].([]model.AccessLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessLogs indicates an expected call of GetAccessLogs.
func (mr *MockMySQLRepositoryInterfaceMockRecorder) GetAccessLogs(ctx, shortCode, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessLogs", reflect.TypeOf((*MockMySQLRepositoryInterface)(nil).GetAccessLogs), ctx, shortCode, limit)
}

// GetDB mocks base method.
func (m *MockMySQLRepositoryInterface) GetDB() interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(interface{})
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockMySQLRepositoryInterfaceMockRecorder) GetDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockMySQLRepositoryInterface)(nil).GetDB))
}

// GetShortLinkByCode mocks base method.
func (m *MockMySQLRepositoryInterface) GetShortLinkByCode(ctx context.Context, shortCode string) (*model.ShortLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShortLinkByCode", ctx, shortCode)
	ret0, _ := ret[0].(*model.ShortLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShortLinkByCode indicates an expected call of GetShortLinkByCode.
func (mr *MockMySQLRepositoryInterfaceMockRecorder) GetShortLinkByCode(ctx, shortCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShortLinkByCode", reflect.TypeOf((*MockMySQLRepositoryInterface)(nil).GetShortLinkByCode), ctx, shortCode)
}

// GetShortLinkByURL mocks base method.
func (m *MockMySQLRepositoryInterface) GetShortLinkByURL(ctx context.Context, url string) (*model.ShortLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShortLinkByURL", ctx, url)
	ret0, _ := ret[0].(*model.ShortLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShortLinkByURL indicates an expected call of GetShortLinkByURL.
func (mr *MockMySQLRepositoryInterfaceMockRecorder) GetShortLinkByURL(ctx, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShortLinkByURL", reflect.TypeOf((*MockMySQLRepositoryInterface)(nil).GetShortLinkByURL), ctx, url)
}

// GetTotalLinksCount mocks base method.
func (m *MockMySQLRepositoryInterface) GetTotalLinksCount(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalLinksCount", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalLinksCount indicates an expected call of GetTotalLinksCount.
func (mr *MockMySQLRepositoryInterfaceMockRecorder) GetTotalLinksCount(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalLinksCount", reflect.TypeOf((*MockMySQLRepositoryInterface)(nil).GetTotalLinksCount), ctx)
}

// SaveAccessLog mocks base method.
func (m *MockMySQLRepositoryInterface) SaveAccessLog(ctx context.Context, accessLog *model.AccessLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAccessLog", ctx, accessLog)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAccessLog indicates an expected call of SaveAccessLog.
func (mr *MockMySQLRepositoryInterfaceMockRecorder) SaveAccessLog(ctx, accessLog interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAccessLog", reflect.TypeOf((*MockMySQLRepositoryInterface)(nil).SaveAccessLog), ctx, accessLog)
}

// SaveShortLink mocks base method.
func (m *MockMySQLRepositoryInterface) SaveShortLink(ctx context.Context, sl *model.ShortLink) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveShortLink", ctx, sl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveShortLink indicates an expected call of SaveShortLink.
func (mr *MockMySQLRepositoryInterfaceMockRecorder) SaveShortLink(ctx, sl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveShortLink", reflect.TypeOf((*MockMySQLRepositoryInterface)(nil).SaveShortLink), ctx, sl)
}

// MockRedisRepositoryInterface is a mock of RedisRepositoryInterface interface.
type MockRedisRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRedisRepositoryInterfaceMockRecorder
}

// MockRedisRepositoryInterfaceMockRecorder is the mock recorder for MockRedisRepositoryInterface.
type MockRedisRepositoryInterfaceMockRecorder struct {
	mock *MockRedisRepositoryInterface
}

// NewMockRedisRepositoryInterface creates a new mock instance.
func NewMockRedisRepositoryInterface(ctrl *gomock.Controller) *MockRedisRepositoryInterface {
	mock := &MockRedisRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRedisRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisRepositoryInterface) EXPECT() *MockRedisRepositoryInterfaceMockRecorder {
	return m.recorder
}

// AddSource mocks base method.
func (m *MockRedisRepositoryInterface) AddSource(ctx context.Context, shortCode, source string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSource", ctx, shortCode, source)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSource indicates an expected call of AddSource.
func (mr *MockRedisRepositoryInterfaceMockRecorder) AddSource(ctx, shortCode, source interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSource", reflect.TypeOf((*MockRedisRepositoryInterface)(nil).AddSource), ctx, shortCode, source)
}

// AddUV mocks base method.
func (m *MockRedisRepositoryInterface) AddUV(ctx context.Context, shortCode, visitorID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUV", ctx, shortCode, visitorID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddUV indicates an expected call of AddUV.
func (mr *MockRedisRepositoryInterfaceMockRecorder) AddUV(ctx, shortCode, visitorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUV", reflect.TypeOf((*MockRedisRepositoryInterface)(nil).AddUV), ctx, shortCode, visitorID)
}

// Close mocks base method.
func (m *MockRedisRepositoryInterface) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRedisRepositoryInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRedisRepositoryInterface)(nil).Close))
}

// ExistsShortLink mocks base method.
func (m *MockRedisRepositoryInterface) ExistsShortLink(ctx context.Context, shortCode string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsShortLink", ctx, shortCode)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsShortLink indicates an expected call of ExistsShortLink.
func (mr *MockRedisRepositoryInterfaceMockRecorder) ExistsShortLink(ctx, shortCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsShortLink", reflect.TypeOf((*MockRedisRepositoryInterface)(nil).ExistsShortLink), ctx, shortCode)
}

// GetClient mocks base method.
func (m *MockRedisRepositoryInterface) GetClient() *redis.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient")
	ret0, _ := ret[0].(*redis.Client)
	return ret0
}

// GetClient indicates an expected call of GetClient.
func (mr *MockRedisRepositoryInterfaceMockRecorder) GetClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockRedisRepositoryInterface)(nil).GetClient))
}

// GetPV mocks base method.
func (m *MockRedisRepositoryInterface) GetPV(ctx context.Context, shortCode string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPV", ctx, shortCode)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPV indicates an expected call of GetPV.
func (mr *MockRedisRepositoryInterfaceMockRecorder) GetPV(ctx, shortCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPV", reflect.TypeOf((*MockRedisRepositoryInterface)(nil).GetPV), ctx, shortCode)
}

// GetShortLink mocks base method.
func (m *MockRedisRepositoryInterface) GetShortLink(ctx context.Context, shortCode string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShortLink", ctx, shortCode)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShortLink indicates an expected call of GetShortLink.
func (mr *MockRedisRepositoryInterfaceMockRecorder) GetShortLink(ctx, shortCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShortLink", reflect.TypeOf((*MockRedisRepositoryInterface)(nil).GetShortLink), ctx, shortCode)
}

// GetSources mocks base method.
func (m *MockRedisRepositoryInterface) GetSources(ctx context.Context, shortCode string) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSources", ctx, shortCode)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSources indicates an expected call of GetSources.
func (mr *MockRedisRepositoryInterfaceMockRecorder) GetSources(ctx, shortCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSources", reflect.TypeOf((*MockRedisRepositoryInterface)(nil).GetSources), ctx, shortCode)
}

// GetUV mocks base method.
func (m *MockRedisRepositoryInterface) GetUV(ctx context.Context, shortCode string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUV", ctx, shortCode)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUV indicates an expected call of GetUV.
func (mr *MockRedisRepositoryInterfaceMockRecorder) GetUV(ctx, shortCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUV", reflect.TypeOf((*MockRedisRepositoryInterface)(nil).GetUV), ctx, shortCode)
}

// IncrementPV mocks base method.
func (m *MockRedisRepositoryInterface) IncrementPV(ctx context.Context, shortCode string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementPV", ctx, shortCode)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementPV indicates an expected call of IncrementPV.
func (mr *MockRedisRepositoryInterfaceMockRecorder) IncrementPV(ctx, shortCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementPV", reflect.TypeOf((*MockRedisRepositoryInterface)(nil).IncrementPV), ctx, shortCode)
}

// SaveShortLink mocks base method.
func (m *MockRedisRepositoryInterface) SaveShortLink(ctx context.Context, shortCode, originalURL string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveShortLink", ctx, shortCode, originalURL, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveShortLink indicates an expected call of SaveShortLink.
func (mr *MockRedisRepositoryInterfaceMockRecorder) SaveShortLink(ctx, shortCode, originalURL, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveShortLink", reflect.TypeOf((*MockRedisRepositoryInterface)(nil).SaveShortLink), ctx, shortCode, originalURL, ttl)
}
