// Code generated by MockGen. DO NOT EDIT.
// Source: internal/mq/interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	mq "octopus/internal/mq"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockProducerInterface is a mock of ProducerInterface interface.
type MockProducerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProducerInterfaceMockRecorder
}

// MockProducerInterfaceMockRecorder is the mock recorder for MockProducerInterface.
type MockProducerInterfaceMockRecorder struct {
	mock *MockProducerInterface
}

// NewMockProducerInterface creates a new mock instance.
func NewMockProducerInterface(ctrl *gomock.Controller) *MockProducerInterface {
	mock := &MockProducerInterface{ctrl: ctrl}
	mock.recorder = &MockProducerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProducerInterface) EXPECT() *MockProducerInterfaceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockProducerInterface) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockProducerInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockProducerInterface)(nil).Close))
}

// SendAccessLog mocks base method.
func (m *MockProducerInterface) SendAccessLog(ctx context.Context, msg *mq.AccessLogMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAccessLog", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAccessLog indicates an expected call of SendAccessLog.
func (mr *MockProducerInterfaceMockRecorder) SendAccessLog(ctx, msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAccessLog", reflect.TypeOf((*MockProducerInterface)(nil).SendAccessLog), ctx, msg)
}

// MockConsumerInterface is a mock of ConsumerInterface interface.
type MockConsumerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockConsumerInterfaceMockRecorder
}

// MockConsumerInterfaceMockRecorder is the mock recorder for MockConsumerInterface.
type MockConsumerInterfaceMockRecorder struct {
	mock *MockConsumerInterface
}

// NewMockConsumerInterface creates a new mock instance.
func NewMockConsumerInterface(ctrl *gomock.Controller) *MockConsumerInterface {
	mock := &MockConsumerInterface{ctrl: ctrl}
	mock.recorder = &MockConsumerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsumerInterface) EXPECT() *MockConsumerInterfaceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockConsumerInterface) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockConsumerInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockConsumerInterface)(nil).Close))
}

// Subscribe mocks base method.
func (m *MockConsumerInterface) Subscribe() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe")
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockConsumerInterfaceMockRecorder) Subscribe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockConsumerInterface)(nil).Subscribe))
}
